{
 "title": "Netology dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU Usage  percent",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (mode) (irate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU LA",
   "type": "timeseries",
   "description": "CPU Load Average",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": " node_load5{instance=\"nodeexporter:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "  node_load15{instance=\"nodeexporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Ram, %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_MemFree_bytes{instance=\"nodeexporter:9100\"}) / (node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\"} )) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free RAM, MB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free FileSystem, %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free FileSystem",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}